# Existing API URLs and keys
GEOCODING_API_URL = "https://maps.googleapis.com/maps/api/geocode/json"
OPEN_METEO_URL = "https://api.open-meteo.com/v1/forecast"
OPENCAGE_API_URL = "https://api.opencagedata.com/geocode/v1/json"
OPENCAGE_API_KEY = "your_opencage_api_key"
GOOGLE_API_KEY = "your_google_api_key"
GOOGLE_CX = "your_google_cx"
GOOGLE_SEARCH_URL = "https://www.googleapis.com/customsearch/v1"
LASTFM_API_KEY = "your_lastfm_api_key"
LASTFM_BASE_URL = "http://ws.audioscrobbler.com/2.0/"
YOUTUBE_SEARCH_URL = "https://www.googleapis.com/youtube/v3/search"
